<p><b>The following topics provide high-level, architectural information on core concepts and objects you will encounter when using OpenShift. Many of these objects come from Kubernetes, which is extended by OpenShift to provide a more feature-rich development lifecycle platform.</b></p>
</p>Containers and images are the building blocks for deploying your applications.</p>
</p>Pods and services allow for containers to communicate with each other and proxy connections.</p>
</p>Builds and image streams allow you to build working images and react to new images.</p>
</p>Deployments add expanded support for the software development and deployment lifecycle.</p>
</p>Routes announce your service to the world.</p>
</p>Templates allow for many objects to be created at once based on customized parameters.</p>

